os:
  - linux
  - osx

language: cpp
sudo: required
osx_image: xcode6.4
dist: trusty

script:
  - cmake .
  - make

compiler:
  - clang
  - gcc

matrix:
  exclude:
  - os: osx
    compiler: gcc

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then source ./travis/linux.install.sh; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ];   then source ./travis/osx.install.sh;   fi

before_deploy:
- if [ "$TRAVIS_OS_NAME" == "osx" ];   then source ./travis/osx.package.sh;   fi

deploy:
  provider: releases
  api_key:
    secure: "SDmI1rknU+c09NwlikEPl0uwpkI+zXHoj38n3pIAKlBxchoycBwoBJpwtRuSQrIT59Sb220xHhjz6WbtHXbko+WlF8Znvd1G9zpIGSopk/gPdbFlGDxbhhBwNqp1YlTGgsHyo2ORaU0KeTyrOBTvZfuzE9tEzK6FrSmL6tXR708="
  file: "NXEngine-*.dmg"
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = osx"