image:
  - macos-mojave
  - Ubuntu1604
  - Ubuntu2004
  - Visual Studio 2017

version: 2.6.5.{build}

pull_requests:
  do_not_increment_build_number: true

configuration: Release

platform:
- x64

build:
  project: nx.sln
  verbosity: minimal

artifacts:
  - path: 'NXEngine-*.zip'
    name: winbuild

  - path: 'NXEngine-*.dmg'
    name: osxbuild

  - path: 'NXEngine-*.flatpak'
    name: flatpakbuild

  - path: 'NXEngine-*.AppImage'
    name: appimagebuild


deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: ''
    auth_token:
      secure: UNAaCG+KMRMqZqVEHpSgXTXZOJlqEQ/7nySQ6U/LutHjXnuqVNpYDxoqIW1hufI+
    draft: true
    force_update: true
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true


for:
-
  matrix:
    only:
      - image: Visual Studio 2017

  before_deploy:
   - ps: .\build-scripts\ci\win.package.ps1


-
  matrix:
    only:
      - image: Ubuntu1604

  install:
    - sudo apt update
    - sudo apt install -yqq libsdl2-dev libsdl2-mixer-dev libpng-dev libxml2-utils jq appstream

  build_script:
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build/AppDir/usr -Bbuild -H.
    - ninja -Cbuild

  before_deploy:
    - build-scripts/build-appimage.sh --no-build

-
  matrix:
    only:
      - image: Ubuntu2004

  install:
    - sudo apt update
    - sudo apt install -yqq flatpak flatpak-builder libxml2-utils
    - flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak-builder --user --install-deps-only --install-deps-from=flathub . org.nxengine.nxengine_evo.json

  build_script:
    - build-scripts/build-flatpak.sh

-
  matrix:
    only:
      - image: macos-mojave

  install:
    - brew update
    - brew install sdl2 sdl2_mixer libpng

  build_script:
    - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -Bbuild -H.
    - make -Cbuild

  before_deploy:
    - brew install create-dmg dylibbundler jq
    - build-scripts/build-macos.sh --no-build

