image:
  - macos
  - Ubuntu1804
  - Visual Studio 2019

version: 2.6.5.{build}

pull_requests:
  do_not_increment_build_number: true

configuration: Release

platform:
- x64

build:
  project: nx.sln
  verbosity: minimal

artifacts:
  - path: 'NXEngine-*.zip'
    name: winbuild

  - path: 'NXEngine-*.dmg'
    name: osxbuild

  - path: 'NXEngine-*.AppImage'
    name: appimagebuild

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  before_deploy:
   - ps: .\build-scripts\ci\win.package.ps1

-
  matrix:
    only:
      - image: Ubuntu1804

  install:
    - sudo apt update
    - sudo apt install -yqq libsdl2-dev libsdl2-mixer-dev libpng-dev ninja-build

  build_script:
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build/AppDir/usr -Bbuild -H.
    - ninja -Cbuild

  before_deploy:
    - sudo apt install -yqq libxml2-utils jq appstream
    - build-scripts/build-appimage.sh --no-build

-
  matrix:
    only:
      - image: macos

  install:
    - brew update
    - brew install sdl2 sdl2_mixer libpng ninja

  build_script:
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -Bbuild -H.
    - ninja -Cbuild

  before_deploy:
    - brew install create-dmg dylibbundler jq
    - build-scripts/build-macos.sh --no-build
    - appveyor PushArtifact NXEngine-Evo-${APPVEYOR_REPO_TAG_NAME}-OSX.dmg
